apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-cluster-manager # use "bind-cluster-viewer" for viewer
subjects:
  - kind: ServiceAccount
    name: account-cluster-manager # use "account-cluster-viewer" for viewer
    namespace: chaos-testing
roleRef:
  kind: ClusterRole
  name: cluster-role-manager # use "cluster-role-viewer" for viewer
  apiGroup: rbac.authorization.k8s.io