kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-role-manager
rules:
  - apiGroups: ['']
    resources: ['pods', 'namespaces']
    verbs: ['get', 'list', 'watch']
  - apiGroups:
      - chaos-mesh.org
    resources: ['*']
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delet